<script>
    require(["jquery", 'underscore', 'Magento_Ui/js/modal/modal'], function ($, _) {
        $(document).ready(function() {

            var documentPadding = 50;
            var firstAttempt = true;
            var lastHeight = 0, curHeight = 0;
            var parentBody = window.parent.document.body;
            var intervalOption = null;
            $('.mfp-preloader', parentBody).css('display', 'none');
            $('.mfp-close', parentBody).css('display', 'block');

            $('.mfp-iframe-holder .mfp-content', parentBody).css('width', '100%');
            $('.mfp-iframe-holder .mfp-content', parentBody).css('height', '100%');
            $('.mfp-iframe-holder', parentBody).addClass('fadeInFromLeft');
            $('.mfp-iframe-scaler iframe', parentBody).css({'opacity': 1});
            $('body').addClass('weltpixel-quickview-slideIn');


            $('.reviews-actions a').attr('target', '_parent');
            $('.product-social-links a').attr('target', '_parent');

            setInterval(function(){
                var windowWidth = $(window.parent.window).width();
                if ((windowWidth < 768) && (intervalOption != 'mobile') ) {
                    $('.mfp-wrap', parentBody).removeClass('mfp-popup-fadeInLeft');
                    if (firstAttempt) {
                        curHeight = $('.page-wrapper').outerHeight(true) + documentPadding;
                    } else {
                        curHeight = $('.page-wrapper').outerHeight(true);
                    }
                    documentHeight = curHeight + "px";
                    if (curHeight != lastHeight) {
                        $('.mfp-iframe-holder .mfp-content', parentBody).animate({
                            'height': documentHeight
                        }, 500);
                        lastHeight = curHeight;
                        firstAttempt = false;
                    }
                    intervalOption = 'mobile';
                } else if ((windowWidth >= 768) && (intervalOption != 'desktop')) {
                    $('.mfp-wrap', parentBody).addClass('mfp-popup-fadeInLeft');
                    intervalOption = 'desktop';
                }
            }, 500);

            $(window).resize(_.debounce(function () {
                var windowWidth = $(window.parent.window).width();
                if ((windowWidth < 768) && (intervalOption == 'mobile') ) {
                    intervalOption = null;
                }
            }, 500));
        });
    });
</script>