<?php $helper = $this->helper("Eighteentech\Buynow\Helper\Data"); ?>
<?php $addtocartId = $helper->getConfig('buynow/general/addtocart_id'); ?>
<?php $buttonTitle = $helper->getConfig('buynow/general/button_title'); ?>
<?php $formId = $addtocartId ? $addtocartId : "product_addtocart_form"; ?>
<input type="hidden" name="redirect_checkout" id="redirect_checkout" value="0" data-checkout-url="<?php echo $this->getUrl('checkout');?>"/>
<button type="button"
			title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
			class="action primary tocart-duplicate"
			id="product-addtocart-button-duplicate" style="display:none">
		<span><?php /* @escapeNotVerified */ echo __('Add to Cart'); ?></span>
	</button>
<div class="buynow-button">
    <button type="submit" title="<?php /* @escapeNotVerified */ echo __($buttonTitle) ?>" id="buy-now" class="action primary" data-mage-init='
    {
        "Eighteentech_Buynow/js/buy-now": {
            "form": "#<?php echo $formId; ?>"
        }
    }
    '>
        <span><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
    </button>
</div>
<script type="text/javascript">
	require(['jquery'],function($){
			$(document).ready(function(){
				/*$(document).on('click', '#buy-now', function(){
					$('#product-addtocart-button').hide();
					$('#product-addtocart-button-duplicate').show();
				});*/
				
				$(document).on('click', '#product-addtocart-button-duplicate', function(){
					$('#product-addtocart-button').show();
					$('#product-addtocart-button').trigger('click');
					$('#product-addtocart-button-duplicate').hide();
				});
			});	
		});
</script>
