<?php $product = $block->getProduct(); ?>
<?php $helper = $this->helper("Eighteentech\Buynow\Helper\Data"); ?>
<?php $buttonTitle = $helper->getConfig('buynow/general/button_title'); ?>

<?php if ($product->isSaleable()) : ?>
    <?php $postParams = $block->getAddToCartPostParams($product); ?>
    <div class="buynow-btn">
        <form action="<?php /* @noEscape */ echo $postParams['action']; ?>"
              id="product_addtocart_form_<?php /* @noEscape */ echo $postParams['data']['product']; ?>"
              method="post">
            <input type="hidden" 
                   name="product"
                   value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
            <input type="hidden"
                   name="<?php /* @noEscape */ echo 'uenc'; ?>"
                   value="<?php /* @noEscape */ echo $postParams['data']['uenc']; ?>">
            <?php echo $block->getBlockHtml('formkey')?>            
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__($buttonTitle)); ?>"
                    class="action tocart buynow primary"
                    data-mage-init='
                    {
                        "Eighteentech_Buynow/js/buy-now": {
                            "form": "#product_addtocart_form_<?php echo $postParams['data']['product']; ?>"
                        }
                    }
                '>
                <span><?php /* @noEscape */ echo __($buttonTitle) ?></span>
            </button>
            <?php 
              if($product->getTypeId()=='configurable'){
				  $attributeIds = $block->getConfigAttributes($product);
				  if(count($attributeIds)){
					  foreach($attributeIds as $attributeId){
						  $buy_now_id = 'buy_now_'.$product->getId().'_'.$attributeId;
						  ?>
						  <input type="hidden" name="super_attribute[<?= $attributeId?>]" id="<?php echo $buy_now_id;?>"/>
						  <?php
					  }
				  }
			  }
            ?>
        </form>
    </div>
<?php endif; ?>
