<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Amp
 */
?>
<?php
/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<a [class]="cart_fullness ? 'amamp-minicart-link -full' : 'amamp-minicart-link -empty'"
   class="amamp-minicart-link"
   href="<?= $block->escapeUrl($block->getShoppingCartUrl()); ?>"
   aria-label="<?= $block->escapeHtml(__('Open cart page')); ?>">
</a>
