<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
    ?>
    <li class="my-account-link">
		<a href="<?php echo $this->getUrl('customer/account');?>">
			<?php echo __('My Account');?>
		</a>
    </li>
    <li class="authorization-link logout">
		<a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
			<?= $block->escapeHtml($block->getLabel()) ?>
		</a>
	</li>
<?php    
}else{
?>
<li class="authorization-link login" data-label="<?= $block->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
        <?= $block->escapeHtml($block->getLabel()) ?>
    </a>
</li>
<?php }?>
