<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Xlanding
 */
?>
<?php
/**
 * @see \Magento\Catalog\Block\Adminhtml\Form\Renderer\Fieldset\Element
 */
?>
<label class="label admin__field-label" for="<?= $this->getHtmlId() ?>" <?= $this->getUiId('label') ?>>
    <span></span>
</label>
<div class="admin__field-control control">
    <span class="admin__control-link"><?= $block->getElementHtml(); ?></span>
</div>
